### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rallisf1** [toriphes/wp-graphql-ninja-forms#8]
PHP 7.4.19
WP 5.8.2
WP GraphQL 1.6.7
Ninja Form 3.6.7

GraphiQL IDE won't load the schema when this plugin is active and standard fetch form query returns an error 500.

**Comment by hmdnprks** [comment]
Any update on this issue?

**Comment by ramil811** [comment]
download and install a pre-released version. I used 0.1.4 and it worked.

**Comment by MuJlblii** [comment]
Maybe someone has a problem with this plugin, after installing it I can`t load GraphiQL IDE, and there is an error in console:
"Uncaught (in promise) Error: Response not successful: Received status code 500".
After deactivating this plugin, everything works fine.
Plugin version 0.1.4
WPGraphQL version 1.14.5
WP version 6.2.2

**Comment by Demiduska** [comment]
Go to tags and choose 1.4 and use it

**Comment by toriphes** [comment]
Hi folks, thanks for your interest on this plugin.
This code was tested on wp 5.8 and wp-graphql 1.6.4 . It is probably no longer compatible with newer versions of wp-graphql.

I will try to figure out the problem.

**Comment by Demiduska** [comment]
> Hi folks, thanks for your interest on this plugin. This code was tested on wp 5.8 and wp-graphql 1.6.4 . It is probably no longer compatible with newer versions of wp-graphql.
> 
> I will try to figure out the problem.

I got this error when uploading the current repo.

```
[19-Jul-2023 09:00:00 UTC] PHP Fatal error:  Uncaught Error: Class 'WPGraphQL\NinjaForms\Enum\Field_Label_Pos_Enums' not found in .../wp-content/plugins/wp-graphql-ninja-forms-master/src/class-type-registry.php:36
Stack trace:
#0 /home/channelchek/dashboard.channelchek.com/wp-includes/class-wp-hook.php(308): WPGraphQL\NinjaForms\Type_Registry->init(Object(WPGraphQL\Registry\TypeRegistry))
#1.../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 .../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 .../wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(285): do_action('graphql_registe...', Object(WPGraphQL\Registry\TypeRegistry))
#4.../wp-includes/class-wp-hook.php(308): WPGraphQL\Registry\TypeRegistry->init_type_registry(Object(WPGraphQL\Registry\TypeRegistry))
#5.../wp-includ in /home/channelchek/dashboard.channelchek.com/wp-content/plugins/wp-graphql-ninja-forms-master/src/class-type-registry.php on line 36
[19-Jul-2023 09:00:00 UTC] PHP Fatal error:  Uncaught Error: Class 'WPGraphQL\NinjaForms\Enum\Field_Label_Pos_Enums' not found in .../plugins/wp-graphql-ninja-forms-master/src/class-type-registry.php:36
```
Thank you for your work!

**Comment by piotrszczesniak** [comment]
I would need this plugin to work with the latest ver of WordPress 🙊🙉🙈
